version: "3.9"
services:
    api:
        container_name: Nimb3s.Automaton.Api
        build:
          context: .
          dockerfile: src/Nimb3s.Automaton.Api/Dockerfile
        environment:
            ASPNETCORE_URLS: "http://+:8000"
            ASPNETCORE_HTTPS_PORT: "8001"
        ports:
            - "8000:8000"
            - "8001:8001"
        depends_on:
            - db
    db:
        container_name: Nimb3s.Automaton.Database
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            SA_PASSWORD: "1234qwerASDF"
            ACCEPT_EULA: "Y"
            MSSQL_PID: Express
        ports:
            - "1433:1433"
