using Nimb3s.Automaton.Messages;
using Nimb3s.Automaton.Messages.Jobs;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Nimb3s.Automaton.Api.Models
{

    /// <summary>
    /// The automation request
    /// </summary>
    public class AutomationJobModel
    {
        /// <summary>
        /// The automation job id generated by our system.
        /// </summary>
        public Guid JobId { get; set; }

        /// <summary>
        /// The automation job name
        /// </summary>
        [Required]
        public string Name { get; set; }

        /// <summary>
        /// The automation job status.
        /// </summary>
        public JobStatus AutomationJobStatus { get; set; }
    }
}
