using Nimb3s.Automaton.Messages.User;
using System;
using System.ComponentModel.DataAnnotations;

namespace Nimb3s.Automaton.Api.Models
{

    /// <summary>
    /// The automation request
    /// </summary>
    public class NewJobModel
    {
        /// <summary>
        /// The automation job name
        /// </summary>
        [Required]
        public string Name { get; set; }

        /// <summary>
        /// The automation job status.
        /// </summary>
        public JobStatusType JobStatus { get; set; }
    }

    /// <summary>
    /// The automation request
    /// </summary>
    public class NewJobCreatedModel
    {
        /// <summary>
        /// The automation job id generated by our system.
        /// </summary>
        public Guid JobId { get; set; }

        /// <summary>
        /// The automation job name
        /// </summary>
        [Required]
        public string Name { get; set; }

        /// <summary>
        /// The automation job status.
        /// </summary>
        public JobStatusType JobStatus { get; set; }
    }

    /// <summary>
    /// The automation request
    /// </summary>
    public class UpdateJobModel
    {
        /// <summary>
        /// The automation job status.
        /// </summary>
        public JobStatusType JobStatus { get; set; }
    }
}
