using System;
using System.ComponentModel.DataAnnotations;

namespace Nimb3s.Automaton.Pocos.Models
{

    /// <summary>
    /// The automation request
    /// </summary>
    public class JobCreatedModel
    {
        /// <summary>
        /// The automation job name
        /// </summary>
        [Required]
        public string Name { get; set; }
    }

    /// <summary>
    /// The automation request
    /// </summary>
    public class NewJobCreatedModel
    {
        /// <summary>
        /// The automation job id generated by our system.
        /// </summary>
        public Guid JobId { get; set; }

        /// <summary>
        /// The automation job name
        /// </summary>
        [Required]
        public string Name { get; set; }

        /// <summary>
        /// The automation job status.
        /// </summary>
        public JobStatusType JobStatus { get; set; }
    }
}
